{{/*apiVersion: v1*/}}
{{/*kind: ConfigMap*/}}
{{/*metadata:*/}}
{{/*  name: fluentd-appointment-service-config*/}}
{{/*data:*/}}
{{/*  fluent.conf: |*/}}
{{/*    <source>*/}}
{{/*      @type tail*/}}
{{/*      path /var/log/appointment-service/*.log*/}}
{{/*      pos_file /fluentd/log/appointment-service.pos*/}}
{{/*      tag appointment-service.log*/}}
{{/*      <parse>*/}}
{{/*        @type none*/}}
{{/*      </parse>*/}}
{{/*    </source>*/}}

{{/*    <match appointment-service.log>*/}}
{{/*      @type stdout  # Replace this with your preferred output plugin*/}}
{{/*      @log_level info*/}}
{{/*    </match>*/}}

{{/*#Create this config on node using*/}}
{{/*#  kubectl apply -f fluentd-gm-user-config.yaml*/}}
