name: Deploy to EKS Fargate (gm-services-cluster)

on:
  push:
    branches:
      - main  # Trigger deployment on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig for EKS cluster
        run: |
          aws eks update-kubeconfig --region us-east-1 --name gm-services-cluster

      - name: Set Helm Image Tag
        run: |
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV  # Optional: replace with Git SHA

      - name: Helm Upgrade - appointment-service
        run: |
          helm upgrade --install appointment-service ./helm-chart \
            --namespace gm-services \
            --create-namespace \
            --set image.repository=tobyawo/appointment-service \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --set service.port=8489 \
            --wait
